name: CI/CD Pipeline

on:
  push:
    branches:
      - main   # Trigger only on pushes to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install dependencies & run tests
      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      # Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        # Removed ecr: auto - not needed for DockerHub login

      # Build Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/node-web-app:latest .

      # Push Docker image
      - name: Push to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/node-web-app:latest
